title: NMFS Openscapes Fall 2022 Tutorials
show_downloads: false
theme: jekyll-theme-slate
github:
  repository_url: https://github.com/RVerse-Tutorials/NMFS-Openscapes-fall-2022
  is_project_page: true
